def setup_finalize
  # 1. Prepare Database
  # We use bin/rails so we use the local bundler environment
  # We set abort_on_failure: false so we can rescue the DuplicateTable error
  
  puts "\n💾  Preparing Database..."
  
  if run("bin/rails db:prepare", abort_on_failure: false)
    puts "    ✅ Database ready."
  else
    puts "\n⚠️   Database conflict detected!" 
    puts "    The database for '#{app_name}' likely already exists from a previous run."
    
    if yes?("    Would you like to DROP the existing database and reset it? (This destroys old data)")
      # We do drop, create, migrate instead of reset to avoid seed issues if seed file is incomplete
      run "bin/rails db:drop db:create db:migrate"
      puts "    ✅ Database reset and migrated."
    else
      puts "    ❌ Database setup skipped. You must resolve this manually."
    end
  end

  # 2. Inject Credentials
  # We construct a hash of the credentials collected during the wizard
  # and inject them into the encrypted credentials file via a runner script.
  creds = {}
  
  # Google / Gemini / Search
  if @gemini_key.present? || @google_search_key.present?
    creds[:google] ||= {}
    creds[:google][:gemini_key] = @gemini_key if @gemini_key.present?
    
    if @google_search_key.present?
      creds[:google][:search] ||= {}
      creds[:google][:search][:api_key] = @google_search_key
      creds[:google][:search][:search_engine_id] = @google_search_id if @google_search_id.present?
    end
  end

  # Stripe
  if @stripe_publishable.present?
    creds[:stripe] ||= {}
    creds[:stripe][:publishable_key] = @stripe_publishable
    creds[:stripe][:secret_key]      = @stripe_secret      if @stripe_secret.present?
    creds[:stripe][:signing_secret]  = @stripe_signing     if @stripe_signing.present?
  end

  # Data.gov
  if @data_gov_key.present?
    creds[:data_gov_key] = @data_gov_key
  end

  if creds.any?
    puts "🔐  Encrypting and saving provided credentials..."
    
    # We create a temporary script to run within the application context
    # This ensures we use the correct master key generated by `rails new`
    create_file "tmp/setup_creds.rb", <<~RUBY
      updates = #{creds.inspect}
      puts "   -> Merging keys: \#{updates.keys.join(', ')}"
      
      # Load existing config
      current = Rails.application.credentials.config
      
      # Deep merge updates
      new_config = current.deep_merge(updates)
      
      # FIX: deep_stringify_keys ensures the YAML is written as "key:" instead of ":key:"
      # This makes the file look standard when opened in an editor.
      Rails.application.credentials.write(new_config.deep_stringify_keys.to_yaml)
    RUBY

    run "bin/rails runner tmp/setup_creds.rb"
    remove_file "tmp/setup_creds.rb"
  end

  # 3. Remove unused Stimulus Controller generated by standard rails
  remove_file "app/javascript/controllers/hello_controller.js"

  # 4. Linting
  run "bundle exec rubocop -a"

  puts "\n🎉  App Generation Complete!"
  puts "    Run 'bin/dev' to start."
  
  if @install_local
    puts "⚠️   REMINDER: Start your Windows Llama Server on port 8080 (0.0.0.0)"
  end
end