def setup_finalize
  # 1. Prepare Database
  # We use bin/rails so we use the local bundler environment
  # We set abort_on_failure: false so we can rescue the DuplicateTable error
  
  puts "\n💾  Preparing Database..."
  
  if run("bin/rails db:prepare", abort_on_failure: false)
    puts "    ✅ Database ready."
  else
    puts "\n⚠️   Database conflict detected!" 
    puts "    The database for '#{app_name}' likely already exists from a previous run."
    
    if yes?("    Would you like to DROP the existing database and reset it? (This destroys old data)")
      # We do drop, create, migrate instead of reset to avoid seed issues if seed file is incomplete
      run "bin/rails db:drop db:create db:migrate"
      puts "    ✅ Database reset and migrated."
    else
      puts "    ❌ Database setup skipped. You must resolve this manually."
    end
  end

  # 2. Remove unused Stimulus Controller generated by standard rails
  remove_file "app/javascript/controllers/hello_controller.js"

  # 3. Linting
  run "bundle exec rubocop -a"

  puts "\n🎉  App Generation Complete!"
  puts "    Run 'bin/dev' to start."
  
  if @install_local
    puts "⚠️   REMINDER: Start your Windows Llama Server on port 8080 (0.0.0.0)"
  end
end