def setup_finalize
  # 1. Prepare Database
  rails_command "db:prepare"

  # 2. Remove unused Stimulus Controller generated by standard rails
  remove_file "app/javascript/controllers/hello_controller.js"

  # 3. Linting
  run "bundle exec rubocop -a"

  puts "\n🎉  App Generation Complete!"
  puts "    Run 'bin/dev' to start."
  
  if @install_local
    puts "⚠️   REMINDER: Start your Windows Llama Server on port 8080 (0.0.0.0)"
  end
end