# partials/stripe.rb

def setup_stripe
  puts "💳  Configuring Stripe..."

  # 1. Initializer
  # Updated to prefer credentials over ENV variables
  create_file 'config/initializers/stripe.rb', <<~RUBY
    Rails.configuration.stripe = {
      publishable_key: Rails.application.credentials.dig(:stripe, :publishable_key) || ENV['STRIPE_PUBLISHABLE_KEY'],
      secret_key:      Rails.application.credentials.dig(:stripe, :secret_key)      || ENV['STRIPE_SECRET_KEY'],
      signing_secret:  Rails.application.credentials.dig(:stripe, :signing_secret)  || ENV['STRIPE_SIGNING_SECRET']
    }

    Stripe.api_key = Rails.configuration.stripe[:secret_key]
  RUBY

  # 2. Webhooks Controller
  create_file 'app/controllers/webhooks_controller.rb', <<~RUBY
    class WebhooksController < ApplicationController
      skip_before_action :verify_authenticity_token

      def create
        payload = request.body.read
        sig_header = request.env['HTTP_STRIPE_SIGNATURE']
        event = nil

        begin
          event = Stripe::Webhook.construct_event(
            payload, sig_header, Rails.configuration.stripe[:signing_secret]
          )
        rescue JSON::ParserError => e
          render json: { error: 'Invalid payload' }, status: 400
          return
        rescue Stripe::SignatureVerificationError => e
          render json: { error: 'Invalid signature' }, status: 400
          return
        end

        # Handle the event
        case event.type
        when 'checkout.session.completed'
          session = event.data.object
          # handle_checkout_session_completed(session)
          Rails.logger.info "💰 Payment succeeded for session: \#{session.id}"
        end

        render json: { message: 'success' }
      end
    end
  RUBY

  # 3. Checkouts Controller
  create_file 'app/controllers/checkouts_controller.rb', <<~RUBY
    class CheckoutsController < ApplicationController
      # If using the Auth partial, you might want to uncomment this:
      # allow_unauthenticated_access only: [:create, :success, :cancel]

      def create
        session = Stripe::Checkout::Session.create(
          payment_method_types: ['card'],
          line_items: [{
            price_data: {
              currency: 'usd',
              product_data: {
                name: 'Rails 8 Template Product',
                description: 'A test product generated by the template.',
              },
              unit_amount: 2000, # $20.00
            },
            quantity: 1,
          }],
          mode: 'payment',
          success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
          cancel_url: checkout_cancel_url,
        )

        redirect_to session.url, allow_other_host: true
      end

      def success
        # In a real app, you would retrieve the session to verify
        # @session = Stripe::Checkout::Session.retrieve(params[:session_id])
      end

      def cancel
      end
    end
  RUBY

  # 4. Routes
  route "post 'webhooks/stripe', to: 'webhooks#create'"
  route "get 'checkout/success', to: 'checkouts#success'"
  route "get 'checkout/cancel', to: 'checkouts#cancel'"
  route "post 'checkout/create', to: 'checkouts#create'"

  # 5. Views
  create_file 'app/views/checkouts/success.html.erb', <<~ERB
    <div class="max-w-md mx-auto mt-10 p-6 bg-green-50 rounded-lg shadow text-center border border-green-200">
      <h1 class="text-3xl font-bold text-green-700 mb-4">Payment Successful!</h1>
      <p class="text-gray-700 mb-6">Thank you for your purchase. The webhook has been received.</p>
      <%= link_to "Return Home", root_path, class: "inline-block bg-green-600 text-white px-6 py-2 rounded hover:bg-green-700 transition" %>
    </div>
  ERB

  create_file 'app/views/checkouts/cancel.html.erb', <<~ERB
    <div class="max-w-md mx-auto mt-10 p-6 bg-red-50 rounded-lg shadow text-center border border-red-200">
      <h1 class="text-3xl font-bold text-red-700 mb-4">Payment Cancelled</h1>
      <p class="text-gray-700 mb-6">You have not been charged. Feel free to try again when you are ready.</p>
      <%= link_to "Return Home", root_path, class: "inline-block bg-gray-600 text-white px-6 py-2 rounded hover:bg-gray-700 transition" %>
    </div>
  ERB

  # 6. Buy Button Helper
  create_file 'app/views/shared/_stripe_button.html.erb', <<~ERB
    <%= button_to "Buy Test Product ($20)", checkout_create_path, data: { turbo: false }, class: "bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded shadow transition duration-200 ease-in-out" %>
  ERB
end