load_partial 'template/wizard/core'
load_partial 'template/wizard/ui'
load_partial 'template/wizard/content'
load_partial 'template/wizard/payments'
load_partial 'template/wizard/ai'
load_partial 'template/wizard/ops'